Repository RedHatQE/firewatch, pull requests merged in 2023-10, with the labels that each got.

#70 Add oharan2 to OWNERS file
  OWNERS
Labels: needs-ok-to-test, verified, size/XS, can-be-merged, branch-main, ApprovedBy-calebevans

#77 Add an option to report success in jira
  README.md
  cli/objects/jira_base.py
  cli/objects/rule.py
  cli/report/report.py
  docs/configuration_guide.md
  tests/unittests/test_firewatch_report.py
Labels: verified, size/L, can-be-merged, branch-main, ApprovedBy-calebevans

#80 [Issue #79] Add --keep-job-dir option and delete the job directory by default.
  cli/objects/configuration.py
  cli/report/__init__.py
  cli/report/report.py
  docs/cli_usage_guide.md
Labels: verified, size/M, can-be-merged, branch-main, CommentedBy-calebevans, ApprovedBy-ascerra, ApprovedBy-oharan2

#85 [Issue #83] Include a list of past bugs of a specific step/failure_type in description of new bugs
  README.md
  cli/objects/jira_base.py
  cli/report/report.py
  tests/unittests/test_firewatch_report.py
Labels: verified, size/L, can-be-merged, branch-main, commented-calebevans, approved-ascerra
