Repository RedHatQE/firewatch, pull requests merged in 2023-09, with the labels that each got.

#46 Use poetry env for tests in tox.ini
  poetry.lock
  pyproject.toml
  tox.ini
Labels: verified, size/L, branch-main, ApprovedBy-calebevans

#48 use `get_logger` for logger from python-simple-logger
  cli/jira_config_gen/jira_config_gen.py
  cli/objects/configuration.py
  cli/objects/failure.py
  cli/objects/jira_base.py
  cli/objects/job.py
  cli/objects/rule.py
  cli/report/report.py
  poetry.lock
  pyproject.toml
  tests/unittests/test_firewatch_jira_config_gen.py
  tests/unittests/test_firewatch_objects_job.py
  tests/unittests/test_firewatch_report.py
Labels: verified, size/L, can-be-merged, branch-main, ApprovedBy-calebevans

#63 OWNERS - Add myakove and rnetser to reviewers
  OWNERS
Labels: verified, size/XS, can-be-merged, branch-main, ApprovedBy-calebevans, ApprovedBy-myakove

#61 Cleanup jira_config_jen code
  cli/jira_config_gen/__init__.py
  cli/jira_config_gen/jira_config_gen.py
Labels: verified, size/S, can-be-merged, branch-main, ApprovedBy-rnetser

#65 [LPTOCPCI-718] Add try/except when loading config JSON
  cli/objects/configuration.py
Labels: verified, size/S, can-be-merged, branch-main, ApprovedBy-ascerra
