Repository RedHatQE/firewatch, pull requests merged in 2023-11, with the labels that each got.

#88 Added catalog-info.yaml file for backstage
  .pre-commit-config.yaml
  catalog-info.yaml
Labels: ok-to-test, verified, size/S, can-be-merged, branch-main, approved-calebevans

#91 corrected the catalog-info.yaml to remove spaces
  catalog-info.yaml
Labels: ok-to-test, verified, size/XS, can-be-merged, branch-main, approved-calebevans

#89 [Issue #53] Change Commands and Arguments to Use a Hyphen Rather Than an Underscore
  .pre-commit-config.yaml
  cli/jira_config_gen/__init__.py
  cli/report/__init__.py
  cli/report/report.py
  development/test.sh
  docs/CONTRIBUTING.md
  docs/cli_usage_guide.md
  docs/configuration_guide.md
Labels: verified, size/M, can-be-merged, branch-main, approved-dfrazzette, approved-myakove, approved-oharan2, approved-madunn

#97 [Issue 52] Force jira_component to be a list of strings
  README.md
  cli/objects/rule.py
  docs/configuration_guide.md
  tests/unittests/test_firewatch_objects_rule.py
Labels: verified, size/S, can-be-merged, branch-main, approved-ascerra

#101 [Issue #100] Move the "report success" functionality configuration to a flag that utilizes `$FIREWATCH_DEFAULT_*` environment variables
  README.md
  cli/objects/configuration.py
  cli/objects/jira_base.py
  cli/objects/rule.py
  cli/report/__init__.py
  cli/report/report.py
  docs/cli_usage_guide.md
  docs/configuration_guide.md
  tests/unittests/test_firewatch_report.py
Labels: verified, size/L, branch-main, approved-Simranpal

#106 [#24, #25, #94] Update and add to firewatch rule functionality
  README.md
  cli/objects/jira_base.py
  cli/objects/rule.py
  cli/report/report.py
  development/env.list
  docs/cli_usage_guide.md
  docs/configuration_guide.md
  tests/unittests/objects/__init__.py
  tests/unittests/objects/rule/test_firewatch_objects_rule.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_classification.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_failure_type.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_group_name.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_group_priority.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_ignore.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_additional_labels.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_affects_version.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_assignee.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_component.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_epic.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_priority.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_project.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_jira_security_level.py
  tests/unittests/objects/rule/test_firewatch_objects_rule_get_step.py
  tests/unittests/objects/test_firewatch_objects_failure.py
  tests/unittests/objects/test_firewatch_objects_job.py
  tests/unittests/test_firewatch_objects_rule.py
Labels: verified, size/XXL, branch-main, approved-Simranpal

#108 Add user dfrazzette as reviewer in OWNERS file.
  OWNERS
Labels: needs-ok-to-test, verified, size/XS, can-be-merged, branch-main, approved-calebevans

#109 [#99] Update Python Version to 3.12 (3.11 still supported in unit tests)
  Dockerfile
  VERSION
  pyproject.toml
  tox.ini
Labels: ok-to-test, verified, size/XS, branch-main, approved-Sau1506mya

#113 Update README to add the FIREWATCH_REPORT_SUCCESS variable from OpenShfit CI ref
  README.md
Labels: verified, size/XS, branch-main
