Repository RedHatQE/firewatch, pull requests merged in 2024-02, with the labels that each got.

#145 Add feature #140: Introduce new label to add to Jira tickets when a job run passes for a previously failing job
  cli/objects/jira_base.py
  cli/report/constants.py
  cli/report/report.py
  tests/e2e/conftest.py
  tests/e2e/test_add_jira_label_to_open_bugs_with_passing_job_run.py
  tests/unittests/conftest.py
  tests/unittests/functions/report/test_firewatch_functions_report_add_label_to_ticket_when_job_run_passes.py
  tests/unittests/objects/jira/test_jira.py
  tests/unittests/resources/templates/firewatch_configs/firewatch_config_sample.json
  tests/unittests/resources/templates/jira_api/fake_comment_response.json
  tests/unittests/resources/templates/jira_api/fake_fields_response.json
  tests/unittests/resources/templates/jira_api/fake_issue.json
  tests/unittests/resources/templates/jira_api/fake_search_response.json
  tests/unittests/resources/templates/jira_api/fake_server_info.json
Labels: verified, size/XXL, can-be-merged, branch-main, approved-calebevans

#149 [#148] Add try/except block around code adding labels to already existing issues
  README.md
  cli/objects/jira_base.py
Labels: verified, size/S, branch-main, approved-Simranpal

#152 revert changes to failure matching logic in failure_rule.py.
  cli/objects/failure_rule.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-calebevans

#153 Catch xml.etree.ElementTree ParseError exception from an invalid XML file
  cli/objects/job.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-calebevans, approved-myakove

#156 WIP: Change file structure, add a cli.py file, update pre-commit, cleanup poetry config
  .flake8
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  cli/__init__.py
  docs/contribution_guide.md
  poetry.lock
  pyproject.toml
  src/__init__.py
  src/cli.py
  src/commands/__init__.py
  src/commands/jira_config_gen.py
  src/commands/report.py
  src/jira_config_gen/__init__.py
  src/jira_config_gen/jira_config_gen.py
  src/objects/__init__.py
  src/objects/configuration.py
  src/objects/failure.py
  src/objects/failure_rule.py
  src/objects/jira_base.py
  src/objects/job.py
  src/objects/rule.py
  src/report/__init__.py
  src/report/constants.py
  src/report/report.py
  src/templates/jira.config.j2
  tests/e2e/conftest.py
  tests/e2e/test_add_jira_label_to_open_bugs_with_passing_job_run.py
  tests/unittests/conftest.py
  tests/unittests/functions/report/report_base_test.py
  tests/unittests/functions/report/test_firewatch_functions_report.py
  tests/unittests/functions/report/test_firewatch_functions_report_add_label_to_ticket_when_job_run_passes.py
  tests/unittests/functions/report/test_firewatch_functions_report_failure_matches_rule.py
  tests/unittests/functions/report/test_firewatch_functions_report_file_jira_issues.py
  tests/unittests/functions/report/test_firewatch_functions_report_filter_priority_rule_pairs.py
  tests/unittests/objects/configuration/configuration_base_test.py
  tests/unittests/objects/configuration/test_firewatch_objects_configuration_get_config_data.py
  tests/unittests/objects/configuration/test_firewatch_objects_configuration_get_default_jira_project.py
  tests/unittests/objects/configuration/test_firewatch_objects_configuration_get_failure_rules.py
  tests/unittests/objects/configuration/test_firewatch_objects_configuration_get_success_rules.py
  tests/unittests/objects/configuration/test_firewatch_objects_configutation.py
  tests/unittests/objects/failure/test_firewatch_objects_failure.py
  tests/unittests/objects/failure_rule/failure_rule_base_test.py
  tests/unittests/objects/failure_rule/test_firewatch_objects_failure_rule.py
  tests/unittests/objects/failure_rule/test_firewatch_objects_failure_rule_matches_failure.py
  tests/unittests/objects/jira/test_jira.py
  tests/unittests/objects/job/job_base_test.py
  tests/unittests/objects/job/test_fail_with_test_failures_should_not_cause_failure_for_ignored_step.py
  tests/unittests/objects/job/test_firewatch_objects_job.py
  tests/unittests/objects/job/test_firewatch_objects_job_check_is_rehearsal.py
  tests/unittests/objects/job/test_firewatch_objects_job_find_failures.py
  tests/unittests/objects/job/test_firewatch_objects_job_find_pod_failures.py
  tests/unittests/objects/job/test_firewatch_objects_job_find_test_failures.py
  tests/unittests/objects/job/test_firewatch_objects_job_get_download_path.py
  tests/unittests/objects/rule/rule_base_test.py
  tests/unittests/objects/rule/test_firewatch_objects_rule.py
  tox.ini
Labels: size/XXL, branch-main, approved-amp-rh
