Repository RedHatQE/firewatch, pull requests merged in 2024-03, with the labels that each got.

#166 Correct URL getting logged to be the right address
  src/report/report.py
Labels: needs-ok-to-test, verified, size/XS, can-be-merged, branch-main, approved-myakove

#167 Change license from GNU-3 to Apache-2.0 and remove Copyright statements
  LICENSE
  poetry.lock
  pyproject.toml
  src/commands/jira_config_gen.py
  src/jira_config_gen/jira_config_gen.py
  src/objects/__init__.py
  src/objects/configuration.py
  src/objects/failure.py
  src/objects/jira_base.py
  src/objects/job.py
  src/objects/rule.py
  src/report/report.py
  tests/__init__.py
  tests/unittests/__init__.py
  tests/unittests/helpers.py
Labels: verified, size/XXL, can-be-merged, branch-main, approved-myakove

#169 Fix #133: prevent further handling of failures marked as ignored
  src/objects/job.py
  tests/e2e/conftest.py
  tests/e2e/templates/jira_configs/jira.config.j2
  tests/unittests/conftest.py
  tests/unittests/objects/job/test_fail_with_test_failures_should_not_cause_failure_for_ignored_step.py
Labels: verified, size/L, can-be-merged, branch-main, approved-calebevans

#171 Make renovate to update all poetry deps in one PR
  renovate.json
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser
