Repository RedHatQE/firewatch, pull requests merged in 2024-05, with the labels that each got.

#190 [ #188 ] Add retires to Jira functions to fix API rate limit related errors
  poetry.lock
  pyproject.toml
  src/objects/jira_base.py
  tests/unittests/objects/jira/test_jira.py
Labels: verified, size/XXL, can-be-merged, branch-main, commented-calebevans, approved-dfrazzette, approved-btjd

#193 Add hierarchy to handle multiple matching rules for a failure
  src/report/report.py
  tests/unittests/functions/report/test_firewatch_functions_report_failure_matches_rule.py
Labels: verified, size/S, can-be-merged, branch-main, approved-calebevans

#192 Add support for Firewatch base config
  src/objects/configuration.py
  tests/unittests/functions/report/test_firewatch_functions_report_failure_matches_rule.py
  tests/unittests/objects/configuration/test_firewatch_objects_configuration_get_config_data.py
Labels: verified, size/L, can-be-merged, branch-main, approved-calebevans
