Repository RedHatQE/firewatch, pull requests merged in 2025-04, with the labels that each got.

#239 Add readme for running tests
  tests/README.md
Labels: verified, size/M, can-be-merged, branch-main, approved-calebevans

#236 Add functionality to check if job is retriggered in same week
  src/objects/job.py
  src/report/report.py
  tests/unittests/objects/job/test_firewatch_objects_job_check_is_retriggered.py
  tests/unittests/objects/job/test_firewatch_objects_job_get_all_build_ids.py
  tests/unittests/objects/job/test_firewatch_objects_job_get_download_path.py
  tests/unittests/objects/job/test_firewatch_objects_job_get_timestamp.py
Labels: verified, size/L, needs-rebase, can-be-merged, branch-main, approved-calebevans

#241 Update fns to use correct gcp storage client and bucket
  src/objects/job.py
  tests/unittests/objects/job/test_firewatch_objects_job_check_is_retriggered.py
  tests/unittests/objects/job/test_firewatch_objects_job_get_all_build_ids.py
  tests/unittests/objects/job/test_firewatch_objects_job_get_timestamp.py
Labels: size/L, branch-main, approved-calebevans

#242 Update retrigger label, logic & fix unit test
  src/report/constants.py
  src/report/report.py
  tests/unittests/objects/job/test_firewatch_objects_job_check_is_retriggered.py
Labels: size/M, branch-main, approved-calebevans, approved-dfrazzette, approved-oharan2, commented-Simranpal, commented-oharan2

#246 Fix the timestamp path
  src/objects/job.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-dfrazzette, approved-shakyav

#245 Update readme info about jira labels
  docs/cli_usage_guide.md
Labels: ok-to-test, verified, size/XS, branch-main, lgtm-oharan2, lgtm-dfrazzette
